LevelObjects={
    [1]={
        ['obstacles']={
            [1]={
                shape='vertical',
                x=VIRTUAL_WIDTH-120,
                y=VIRTUAL_HEIGHT-TILE_SIZE-110/2
            },
            [2]={
                shape='vertical',
                x=VIRTUAL_WIDTH-35,
                y=VIRTUAL_HEIGHT-TILE_SIZE-110-35-110/2
            },
            [3]={
                shape='vertical',
                x=VIRTUAL_WIDTH-35,
                y=VIRTUAL_HEIGHT-TILE_SIZE-110/2
            },
            [4]={
                shape='vertical',
                x=VIRTUAL_WIDTH-120,
                y=VIRTUAL_HEIGHT-TILE_SIZE-110-35-110/2
            },
            [5]={
                shape='horizontal',
                x=VIRTUAL_WIDTH-80,
                y=VIRTUAL_HEIGHT-TILE_SIZE-110-35/2
            },
            [6]={
                shape='horizontal',
                x=VIRTUAL_WIDTH-80,
                y=VIRTUAL_HEIGHT-TILE_SIZE-110-35-110-35/2
            }
        },
        ['aliens']={
            [1]={
                shape='square',
                x=VIRTUAL_WIDTH-80,
                y=VIRTUAL_HEIGHT-TILE_SIZE-ALIEN_SIZE/2,
                userData='Alien'
            },
            [2]={
                shape='square',
                x=VIRTUAL_WIDTH-80,
                y=VIRTUAL_HEIGHT-35-110-35-35/2,
                userData='Alien'
            }
        }
    }
}